# Jekyll configuration for GitHub Pages
title: MirageVD
description: Lightweight virtual display solution for macOS

# Theme configuration
theme: jekyll-theme-architect

# Site settings
baseurl: "" # the subpath of your site
url: "" # the base hostname & protocol for your site

